name: 'Build Totem USB Debugging'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '[ "seeeduino_xiao_ble" ]'
      shield: '[ "totem_left","totem_right", "totem_dongle" ]'
      alphas: '[ "qwerty" ]'
      nav: '[ "vi" ]'
